variables:
  jets:
    inputs:
    - pt
    - eta
    - mass
    - energy
    - Qw_clusterSoftDrop
    - C2_clusterSoftDrop
    - D2_clusterSoftDrop
    - Tau1_clusterSoftDrop
    - Tau2_clusterSoftDrop
    - Tau3_clusterSoftDrop
    - Tau4_clusterSoftDrop
    - Tau21_clusterSoftDrop
    - Tau32_clusterSoftDrop
    - ECF1_clusterSoftDrop
    - ECF2_clusterSoftDrop
    labels:
    - isDisplaced
  tracks:
    inputs:
    - d0
    - z0SinTheta
    - dphi
    - deta
    - qOverP
    - chiSquared
    - radiusOfFirstHit
    - theta
    - numberDoF
    - pt
    - z0RelativeToBeamspot
    - z0RelativeToBeamspotUncertainty
    - IP3D_signed_d0_significance
    - IP3D_signed_z0_significance
    - phiUncertainty
    - thetaUncertainty
    - qOverPUncertainty
    - z0SinThetaUncertainty
    - numberOfPixelHits
    - numberOfSCTHits
    - numberOfSCTHoles
    - numberOfInnermostPixelLayerHits
    - numberOfPixelSharedHits
    - numberOfSCTSharedHits
    - pt_log1p
    - d0_log1p
    - valid
    labels:
    - truthOriginLabel
    - truthVertexIndex
    - VSIVertexIndex
background:
  name: background
  equal_jets: false
  pattern: &id002
  - user.jburzyns.801168.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801168.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801169.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801169.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801170.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801170.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801171.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801171.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801172.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801172.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801173.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801173.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801174.e8514_s4159_r15224_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
  - user.jburzyns.801174.e8514_s4162_r14622_p6463.tdd.minimal_LRT_fat.25_0_6.Valentine2024-125-g9ae56e6_output.h5/*.h5
global_cuts:
  train:
  - - eventNumber
    - '%10<='
    - 7
  val:
  - - eventNumber
    - '%10=='
    - 8
  test:
  - - eventNumber
    - '%10=='
    - 9
global:
  jets_name: jets
  batch_size: 500000
  num_jets_estimate: 2000000
  base_dir: /ourdisk/hpc/ouhep/jburzyns/dont_archive/
  out_dir: upp/vae_background/output
  components_dir: upp/vae_background/components
  ntuple_dir: tdd_output
  flavour_config: /home/jburzyns/ATLAS/EmergingJets/preprocessing/configs/flavours.yaml
allpt:
  name: allpt
  cuts: &id001
  - - pt
    - '>'
    - 200000
components:
- region:
    name: allpt
    cuts: *id001
  sample:
    name: background
    equal_jets: false
    pattern: *id002
  flavours:
  - promptjet
  num_jets: 10000000
resampling:
  target: promptjet
  method: none
  sampling_fraction: 1.0
  variables:
    pt:
      bins:
      - - 200000
        - 400000
        - 10
      - - 400000
        - 800000
        - 10
      - - 800000
        - 1300000
        - 10
      - - 1300000
        - 3900000
        - 10
    eta:
      bins:
      - - -2.5
        - 2.5
        - 25
upp_hash: v0.3.0
